version: '3.7'

services:
  gopyazo:
    image: beryju/gopyazo
    command: server
    ports:
      - 8000:8000
    environment:
      # Run `docker run -it --rm beryju/gopyazo generate-key` to get a secret key for session
      # GOPYAZO_SECRET: "output"

      # Run `docker run -it --rm beryju/gopyazo hash-password` to get a password hash
      # if you want to use the webinterface
      # GOPYAZO_USER: "username"
      # GOPYAZO_PASSWORD: "output"
    volumes:
      - ./share:/share
