version: '3.7'

services:
  gopyazo:
    image: beryju/gopyazo
    command: server
    ports:
      - 8000:8000
    environment:
      # Set GOPYAZO_SECRET from the output of `docker run -it --rm beryju/gopyazo generate-key`
    volumes:
      - ./share:/share
